### ISSUE TITLE
Do something

### ISSUE THREAD

**Issue by 2uan2** [3-I-Projects/QAirline#1]
@GoatYogurt QAirline stands for QuansAirline

**Comment by 2uan2** [comment]
@DuongGiaHuan-hub lam gi do di

**Comment by 2uan2** [comment]
dung django lam backend nhi, co template day cho ong tha ho dung nhe quan

**Comment by GoatYogurt** [comment]
Dùng framework khác, dùng mấy cái phổ biến í chứ python không được tối ưu cho làm web

**Comment by 2uan2** [comment]
Django tối ưu chứ, chạy API backend thôi mà, trên mạng ngta dùng và dạy đầy, mấy khóa fullstack trên coursera t tìm để định apply financial aid dạy đầy, CS50Web t học r cx dùng Django:v

**Comment by GoatYogurt** [comment]
mới ngày nào còn quyết định dùng cái j cho backend, frontend
